## This file was autogenerated using the EnumreatedTable plugin.
## Do not edit manually!
class_name CharacterAttributes
extends Object


static var FAITH = preload("res://game_resources/character_attributes/attr_faith.tres")
static var FINESSE = preload("res://game_resources/character_attributes/attr_finesse.tres")
static var FLESH = preload("res://game_resources/character_attributes/attr_flesh.tres")
static var INSIGHT = preload("res://game_resources/character_attributes/attr_insight.tres")
static var WILL = preload("res://game_resources/character_attributes/attr_will.tres")

func get_all() -> Array[CharacterAttribute]:
    return [
        FAITH,
        FINESSE,
        FLESH,
        INSIGHT,
        WILL,
    ]
