## This file was autogenerated using the EnumreatedTable plugin.
## Do not edit manually!
class_name Terms
extends Object


static var PROF_L1: Term
static var PROF_L2: Term
static var PROF_L3: Term


static func _static_init() -> void:
	PROF_L1 = preload("res://game_resources/terms/term_prof_l1.tres")
	PROF_L2 = preload("res://game_resources/terms/term_prof_l2.tres")
	PROF_L3 = preload("res://game_resources/terms/term_prof_l3.tres")


static func get_all() -> Array[Term]:
	return [
		PROF_L1,
		PROF_L2,
		PROF_L3,
	]
