## This file was autogenerated using the EnumreatedTable plugin.
## Do not edit manually!
class_name Skills
extends Object


static var ACCURACY: Skill
static var ATTACK: Skill
static var DEFENSE: Skill
static var FIRE_RESISTANCE: Skill
static var HP: Skill
static var INITIATIVE: Skill
static var MOVEMENT: Skill
static var REACH: Skill


static func _static_init() -> void:
	ACCURACY = load("res://game_resources/skills/skill_accuracy.tres")
	ATTACK = load("res://game_resources/skills/skill_attack.tres")
	DEFENSE = load("res://game_resources/skills/skill_defense.tres")
	FIRE_RESISTANCE = load("res://game_resources/skills/skill_fire_resistance.tres")
	HP = load("res://game_resources/skills/skill_hp.tres")
	INITIATIVE = load("res://game_resources/skills/skill_initiative.tres")
	MOVEMENT = load("res://game_resources/skills/skill_movement.tres")
	REACH = load("res://game_resources/skills/skill_reach.tres")


static func get_all() -> Array[Skill]:
	return [
		ACCURACY,
		ATTACK,
		DEFENSE,
		FIRE_RESISTANCE,
		HP,
		INITIATIVE,
		MOVEMENT,
		REACH,
	]
