## This file was autogenerated using the EnumreatedTable plugin.
## Do not edit manually!
class_name Traits
extends Object


static var ARCANE := preload("res://game_resources/traits/trait_arcane.tres")
static var ENDS_TURN := preload("res://game_resources/traits/trait_ends_turn.tres")
static var HAND_CASTED := preload("res://game_resources/traits/trait_hand_casted.tres")

static func get_all() -> Array[TraitTerm]:
    return [
        ARCANE,
        ENDS_TURN,
        HAND_CASTED,
    ]
